### GET /restaurantes
GET http://localhost:3333/restaurantes
Accept: application/json

### POST /restaurantes
POST http://localhost:3333/restaurantes
Authorization: Bearer
Content-Type: application/json

{
  "name": "Restaurante 9",
  "description": "Descripcion del restaurante 9",
  "address" : "Calle 21, 22, 23",
  "phone": "934567895"
}

### GET /restaurantes/:id
GET http://localhost:3333/restaurantes/5
Accept: application/json

### PUT /restaurantes/:id
PUT http://localhost:3333/restaurants/14
Content-Type: application/json

{
  "name": "Restaurante 4 update",
  "description": null,
  "address" : null,
  "phone": null
}

### DELETE /restaurantes/:id
DELETE http://localhost:3333/restaurants/9

